version: "3.7"
services:
  app:
    build: ./
    env_file:
      - .env
    mem_limit: 256m
    depends_on:
      - database
    ports:
      - "8080:8080"
  database:
    image: "postgres:12"
    env_file:
      - .env
    ports:
      - "5432:5432"
